# Generated by Django 2.1.5 on 2019-02-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190203_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Address'),
        ),
    ]
