# Generated by Django 2.1.5 on 2019-02-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_slot_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('R', 'Reserved'), ('C', 'Confirmed')], default='O', max_length=1),
        ),
    ]
