# Generated by Django 2.1.5 on 2019-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_slot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
