# Generated by Django 2.1.5 on 2019-01-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20190128_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='categorystuff',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
